app_version: 0.4.0-preview.2
behavior_configs:
- base_move_speed: 5
  base_wheel_speed: 16.0
  free_mode_auto_off_s: 10
  grid_action_level: subgrid
  hide_cursor_on_click: false
  hide_location: bottom_left
  initial_action_location: system_cursor
  initial_overlay_monitor: with_keyboard_focus
  move_duration_ms: 100
  move_real_cursor_with_virtual: false
  move_speed_multiplier: 3
  movement_easing: 0.1
  multi_action_timeout_ms: 400
  name: main_behavior
  send_escape_after_global_alt_tap__windows: true
  tap_threshold_ms: 200
  wheel_easing: 0.1
  wheel_speed_multiplier: 4.0
  wheel_step_size: 100.0
  wheel_step_size_large: 500.0
classname: AppConfig
custom_monitor_assignments: []
display_input: none
event_tap_location: hid_head
grid_configs:
- always_show_subgrid: false
  grid_defn:
  - border_width: 0.0
    callback: build_cell_strings
    keys: QWERT ASDFG ZXCVB YUIOP HJKL; NM,./
    num_cells_x: 5
    num_cells_y: 6
  - border_width: 1.0
    callback: build_cell_strings
    keys: ''
    num_cells_x: 5
    num_cells_y: 6
  - border_width: 0.0
    callback: apply_strings_and_subgrid_to_cells
    keys: ''
    num_cells_x: 2
    num_cells_y: 1
  hold_subgrid_key_for_nudge: false
  name: position_based
  nudges_per_cell: 4
  strategy: subgrid
  subgrid_dims:
  - 8
  - 3
  subgrid_mouse_action_keys: QWER UIOP ASDF JKL; ZXCV M,./
keyboard_layout:
  id: com.apple.keylayout.US
  name: U.S.
  vk_to_char:
    0:
    - a
    - A
    1:
    - s
    - S
    2:
    - d
    - D
    3:
    - f
    - F
    4:
    - h
    - H
    5:
    - g
    - G
    6:
    - z
    - Z
    7:
    - x
    - X
    8:
    - c
    - C
    9:
    - v
    - V
    10:
    - "\xA7"
    - "\xB1"
    11:
    - b
    - B
    12:
    - q
    - Q
    13:
    - w
    - W
    14:
    - e
    - E
    15:
    - r
    - R
    16:
    - y
    - Y
    17:
    - t
    - T
    18:
    - '1'
    - '!'
    19:
    - '2'
    - '@'
    20:
    - '3'
    - '#'
    21:
    - '4'
    - $
    22:
    - '6'
    - ^
    23:
    - '5'
    - '%'
    24:
    - '='
    - +
    25:
    - '9'
    - (
    26:
    - '7'
    - '&'
    27:
    - '-'
    - _
    28:
    - '8'
    - '*'
    29:
    - '0'
    - )
    30:
    - ']'
    - '}'
    31:
    - o
    - O
    32:
    - u
    - U
    33:
    - '['
    - '{'
    34:
    - i
    - I
    35:
    - p
    - P
    36: "\r"
    37:
    - l
    - L
    38:
    - j
    - J
    39:
    - ''''
    - '"'
    40:
    - k
    - K
    41:
    - ;
    - ':'
    42:
    - \
    - '|'
    43:
    - ','
    - <
    44:
    - /
    - '?'
    45:
    - n
    - N
    46:
    - m
    - M
    47:
    - .
    - '>'
    48: "\t"
    49: ' '
    50:
    - '`'
    - '~'
    51: "\b"
    52: "\x03"
    53: "\e"
    65: .
    66:
    - "\x1D"
    - '*'
    67: '*'
    69: +
    70:
    - "\x1C"
    - +
    71: "\e"
    72:
    - "\x1F"
    - '='
    75: /
    76: "\x03"
    77:
    - "\x1E"
    - /
    78: '-'
    81: '='
    82: '0'
    83: '1'
    84: '2'
    85: '3'
    86: '4'
    87: '5'
    88: '6'
    89: '7'
    91: '8'
    92: '9'
    96: "\x10"
    97: "\x10"
    98: "\x10"
    99: "\x10"
    100: "\x10"
    101: "\x10"
    102: "\x10"
    103: "\x10"
    104: "\x10"
    105: "\x10"
    106: "\x10"
    107: "\x10"
    108: "\x10"
    109: "\x10"
    110: "\x10"
    111: "\x10"
    112: "\x10"
    113: "\x10"
    114: "\x05"
    115: "\x01"
    116: "\v"
    117: "\x7F"
    118: "\x10"
    119: "\x04"
    120: "\x10"
    121: "\f"
    122: "\x10"
    123: "\x1C"
    124: "\x1D"
    125: "\x1F"
    126: "\x1E"
keymaps:
- entries:
    back mouse button: Ctrl+o
    back mouse button (w/o overlay): null
    close UI element: Escape
    cycle click count: null
    cycle font: null
    cycle font reverse: null
    cycle grid action level: null
    cycle mouse action type: null
    cycle mouse button: null
    decrease overlay opacity: ArrowDown
    edit config: Command+,
    enter free mode: null
    execute mouse action:
    - Space
    - Enter
    execute mouse move: null
    exit free mode: Escape
    forward mouse button: Ctrl+i
    forward mouse button (w/o overlay): null
    hide overlay:
    - F13
    - Escape
    hold for back button: null
    hold for drag: ControlLeft
    hold for forward button: null
    hold for middle button: CommandLeft
    hold for move: ShiftLeft
    hold for right button: OptionLeft
    hold for speed decrease: ControlLeft
    hold for speed increase: ShiftLeft
    increase overlay opacity: ArrowUp
    jump to bottom: null
    jump to left edge: null
    jump to right edge: null
    jump to top: null
    left mouse button: space
    left mouse button (w/o overlay): null
    middle mouse button: Cmd+space
    middle mouse button (w/o overlay): null
    move down: S
    move left: A
    move right: D
    move up: W
    release hold/drag: null
    repeat last mouse action: null
    right mouse button: Opt+space
    right mouse button (w/o overlay): null
    show overlay: F13
    subgrid nudge down: null
    subgrid nudge left: null
    subgrid nudge right: null
    subgrid nudge up: null
    switch monitor left: null
    switch monitor right: Tab
    toggle continuous mode: null
    toggle continuous mode until closed: Command+F13
    toggle free mode: F14
    toggle overlay: null
    toggle overlay lock: null
    undo last key:
    - ShiftLeft tap
    - Backspace
    - Option+Backspace
    wheel down: null
    wheel down fast: J
    wheel left: null
    wheel left fast: H
    wheel right: null
    wheel right fast: L
    wheel step down: null
    wheel step down large: null
    wheel step left: null
    wheel step left large: null
    wheel step right: null
    wheel step right large: null
    wheel step up: null
    wheel step up large: null
    wheel up: null
    wheel up fast: K
  name: mac
monitor_assignment_mode: auto
name: ''
style_configs:
- always_on_subgrid_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.2
  background_rgba:
  - 0.47843137254901963
  - 0.28627450980392155
  - 0.28627450980392155
  - 0.8
  char_spacing_cell_width_ratio: 0.5
  char_spacing_font_size_ratio: 0.5
  char_spacing_strategy: cell_width_relative
  cursor_drag_rgba:
  - 0.0
  - 0.5
  - 1.0
  - 0.7
  cursor_move_rgba:
  - 0.75
  - 0.41
  - 0.92
  - 0.7
  cursor_other_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.7
  cursor_rgba:
  - 1.0
  - 0.54
  - 0.0
  - 0.7
  cursor_right_button_rgba:
  - 0.92
  - 0.32
  - 0.32
  - 0.7
  cursor_size: 7
  font_family: HackNF-Bold
  font_size_multiplier: 0.5
  font_weight: 500
  grid_line_style: lines
  grid_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.0
  highlight_animation_ms: 0
  highlight_rgba:
  - 0.7215686274509804
  - 0.4627450980392157
  - 0.44313725490196076
  - 0.5
  name: default
  show_initial_highlight: false
  subgrid_font_size_multiplier: 0.85
  subgrid_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.0
  subgrid_text_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  text_rgba:
  - 0.996078431372549
  - 0.996078431372549
  - 0.996078431372549
  - 1.0
  text_shadow_blur_radius: 1.0
  text_shadow_offset:
  - 2.0
  - -1.0
  text_shadow_rgba:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  text_y_offset: 0
  window_opacity: 0.8
