function fish_add_fallback_completion --description "Generate fish completion file that delegates to zsh completions"
    argparse 'dotfiles' -- $argv
    or return 1

    if test (count $argv) -ne 1
        echo "Usage: fish_add_fallback_completion [--dotfiles] <command>"
        return 1
    end

    set cmd $argv[1]

    if set -q _flag_dotfiles
        set target_dir ~/.config/fish/completions
    else
        set target_dir ~/.local_dotfiles/fish/completions
    end

    mkdir -p $target_dir
    set target_file $target_dir/$cmd.fish

    echo "\
# Generated by fish_add_fallback_completion
function __fish_zsh_fallback_complete_$cmd
    set tokens (commandline -opc)
    set current (commandline -ct)
    zsh-capture-completion \"\$tokens \$current\" 2>/dev/null
end

complete -c $cmd -f -a '(__fish_zsh_fallback_complete_$cmd)'" >$target_file

    echo "Created $target_file"
end
