abbr gm 'git commit -m'
abbr gs 'git status'
abbr gd 'git diff'
abbr ga 'git add'
abbr gp 'git push'
abbr vim nvim
abbr gu 'git reset HEAD'
abbr gco 'git checkout'
abbr gf 'git fetch'
abbr gcal 'gcalcli --defaultCalendar thalesmello@gmail.com --calendar Profissional'
abbr be 'bundle exec'
abbr how 'how2 -l'
abbr gblame 'git log -p -M --follow --stat --'
abbr gr 'git remote'
abbr wd prj
