# vi: ft=ruby
brew "diff-so-fancy"
brew "entr"
brew "fzf"
brew "python3"
brew "neovim"
brew "fish"
brew "node"
brew "tmux"
brew "tldr"
brew "coreutils"
brew "universal-ctags"
brew "pipx"
brew "zoxide"
brew "gh"
brew "the_silver_searcher"
brew "black"
brew "terminal-notifier"
brew "yq"
brew "luarocks"
brew "wget"
brew "jq"
brew "gron"
brew "up"
brew "rg"
brew "nictap/tap/ooo"
brew "yqrashawn/goku/goku"
brew "patchutils"
brew "blueutil"
brew "koekeishiya/formulae/yabai"
brew "koekeishiya/formulae/skhd"
brew "FelixKratz/formulae/sketchybar"
brew "FelixKratz/formulae/svim"
brew "FelixKratz/formulae/borders"
cask "th-ch/youtube-music/youtube-music"
brew "mas"
brew "stow"
brew "pre-commit"


brew "waydabber/betterdisplay/betterdisplaycli" if OS.mac?
brew "choose-gui" if OS.mac?

cask "docker"
cask "iterm2"
cask "pycharm"
cask "whatsapp"
cask "mouse-fix"
cask "font-inconsolata-go-nerd-font"
cask "font-hack-nerd-font"
cask "bettertouchtool"
cask "finicky"
cask "obsidian"
cask "notunes"
cask "karabiner-elements"
cask "rectangle-pro"
cask "betterdisplay"
cask "homerow"
cask "superwhisper"
cask "mouseless@preview"
cask "sf-symbols"
cask "bartender"
cask "zen"
