#!/usr/bin/env fish

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa

set configs

set -a configs menubar_opacity              1.0
set -a configs mouse_follows_focus          off
# # Config should be used in case an external bar is used again
# set -a configs external_bar all:$(sketchybar --query bar | jq .height):0 \
set -a configs focus_follows_mouse          off
set -a configs display_arrangement_order    default
set -a configs window_origin_display        default
set -a configs window_placement             second_child
set -a configs window_insertion_point       last
set -a configs window_zoom_persist          on
set -a configs window_shadow                on
set -a configs window_animation_duration    0.0
set -a configs window_animation_easing      ease_out_circ
set -a configs window_opacity_duration      0.0
set -a configs active_window_opacity        1.0
set -a configs normal_window_opacity        0.90
set -a configs window_opacity               off
set -a configs insert_feedback_color        0xffd75f5f
set -a configs split_ratio                  0.50
set -a configs split_type                   auto
set -a configs auto_balance                 off
set -a configs top_padding                  10
set -a configs bottom_padding               10
set -a configs left_padding                 10
set -a configs right_padding                10
set -a configs window_gap                   10
set -a configs layout                       stack
set -a configs mouse_modifier               fn
set -a configs mouse_action1                move
set -a configs mouse_action2                resize
set -a configs mouse_drop_action            swap


# global settings
yabai -m config $configs

yabai -m rule --add app="iTerm2" manage=off
yabai -m rule --add app="Activity Monitor" manage=off
yabai -m rule --add app="Shottr" manage=off
yabai -m rule --add app="System Settings" manage=off
yabai -m rule --add app="mouseless" manage=off
yabai -m rule --add app="BetterTouchTool" title="BetterTouchTool Settings" manage=off
yabai -m rule --add app="BetterTouchTool" title="Variables \& Scripting" manage=off
yabai -m rule --add app="Google Chrome" title='^Picture in Picture$' manage=off
yabai -m rule --add app="Google Chrome" title='^.*picture-in-picture.*$' manage=off
yabai -m rule --add app="Google Chrome" title='^$' role="AXWindow" subrole="AXStandardWindow" manage=off
yabai -m rule --add app="Karabiner-Elements" title="Karabiner-Elements Settings" manage=off
yabai -m rule --add app="Mac Mouse Fix" manage=off
yabai -m rule --add app="Raycast" manage=off
yabai -m rule --add app="Cisco Secure Client" manage=off
yabai -m rule --add role="AXWindow" manage=off

yabai -m signal --add event=space_changed label=announce_space_change action="display-message \"Space \$YABAI_SPACE_INDEX\""

yabai -m signal --add event=window_resized action="/opt/homebrew/bin/fish -c \"yabai-preset store-window-position \$YABAI_WINDOW_ID\""
yabai -m signal --add event=window_moved action="/opt/homebrew/bin/fish -c \"yabai-preset store-window-position \$YABAI_WINDOW_ID\""

yabai -m signal --add event=window_created label=stack_new_windows action="/opt/homebrew/bin/fish -c \"yabai-preset stack-new-window \$YABAI_WINDOW_ID\""

echo "yabai configuration loaded.."
display-message "yabai configuration loaded.."

