brew install diff-so-fancy
brew install entr
brew install fzf
brew install python3
brew install neovim
brew install fish
brew install node
brew install tmux
brew install tldr
brew install coreutils
brew install universal-ctags
brew install pipx
brew install zoxide
brew install gh
brew install the_silver_searcher
